### ISSUE TITLE
How to add CORS

### ISSUE THREAD

**Issue by maxime-d** [djones/grape-goliath-example#1]
Hello,

How to add CORS in rack config ?
I test use a gem https://github.com/cyu/rack-cors but he doesn't work.

Any idea ?

Thanks

**Comment by maxime-d** [comment]
Resolved with [200, {"Content-Type"=>"application/json", "Access-Control-Allow-Origin" => "*"}, {response: "Hello"}]

**Comment by djones** [comment]
:+1: glad you got it sorted.
